### ISSUE TITLE
[BUG]: Fail to build with boost 1.87

### ISSUE THREAD

**Issue by yizhao1** [COVESA/vsomeip#853]
### vSomeip Version

v3.5.4

### Boost Version

1.87.0

### Environment

Linux

### Describe the bug

vsomeip 3.5.4 cannot be built with boost 1.87:

implementation/endpoints/src/virtual_server_endpoint_impl.cpp: In member function 'virtual void vsomeip_v3::virtual_server_endpoint_impl::prepare_stop(const vsomeip_v3::endpoint::prepare_stop_handler_t&, vsomeip_v3::service_t)':
implementation/endpoints/src/virtual_server_endpoint_impl.cpp:31:9: error: 'class boost::asio::io_context' has no member named 'post'
   31 |     io_.post([ptr, _handler]() { _handler(ptr); });
      |         ^~~~ 

implementation/endpoints/src/tp_reassembler.cpp: In member function 'void vsomeip_v3::tp::tp_reassembler::stop()':
implementation/endpoints/src/tp_reassembler.cpp:167:26: error: no matching function for call to 'boost::asio::basic_waitable_timer<std::chrono::_V2::steady_clock>::cancel(boost::system::error_code&)'
  167 |     cleanup_timer_.cancel(ec);
      |     ~~~~~~~~~~~~~~~~~~~~~^~~~

implementation/endpoints/src/tp_reassembler.cpp: In member function 'void vsomeip_v3::tp::tp_reassembler::cleanup_timer_start_unlocked(bool)':
implementation/endpoints/src/tp_reassembler.cpp:177:24: error: 'boost::asio::steady_timer' {aka 'class boost::asio::basic_waitable_timer<std::chrono::_V2::steady_clock>'} has no member named 'expires_from_now'
  177 |         cleanup_timer_.expires_from_now(std::chrono::seconds(5));
      |                        ^~~~~~~~~~~~~~~~

**Comment by duartenfonseca** [comment]
we currently don't support it but we are trying to update vsomeip-lib to be able for that
